Solution to Mars Rover with test
nilenso/priyanga-mars-rover pull request #1
Opened 2021-08-04 05:29 UTC by PriyangaPKini

2021-08-04 07:39 UTC, jysandy requested changes
I had a long discussion with @PriyangaPKini explaining in detail the changes to be made. I've left some brief comments as a general indicator of what should be changed.

2021-08-04 07:39 UTC, jysandy commented on src/mars_rover/core.clj
> +(defn read-file
This function is doing too many things. It's reading the file, and splitting it into lines. As discussed over call, we can instead inline this and use the `->` macro.

2021-08-04 07:39 UTC, jysandy commented on src/mars_rover/core.clj
> +    "N" (is-with-in-boundry? [x (+ y 1) orientation])
Checking whether the new state is within the boundary should be done in this function.

2021-08-04 07:39 UTC, jysandy commented on src/mars_rover/core.clj
> +  [[x y orientation :as state] instruction]
The rover state should be modelled as a map, not a vector.

2021-08-04 07:39 UTC, jysandy commented on test/mars_rover/core_test.clj
> +(def root-path "/Users/priyangapkini/Clojure/mars-rover/mars-rover/src/mars_rover/")
We should use a relative path here. These tests will only run on Priyanga's computer.

2021-08-04 07:39 UTC, jysandy commented on src/mars_rover/input.txt
> +5 5
This file should be moved to `resources`, it shouldn't be in the `src` folder.

2021-08-04 07:39 UTC, jysandy commented on src/mars_rover/input1.txt
> +
This file should be moved to `resources`, it shouldn't be in the src folder.

2021-08-09 09:03 UTC, ssrihari requested changes

2021-08-09 09:03 UTC, ssrihari commented on src/mars_rover/core.clj
> +  [[x y orientation :as state] instruction]
"state" is not a good name, it doesn't represent what it holds, and is a generic word like `data`, `details`, `info`, etc.

2021-08-09 09:03 UTC, ssrihari commented on src/mars_rover/core.clj
> +  (let [x (to-int x) y (to-int y)]
Separate the concerns of parsing input from actually moving the rover.

2021-08-09 09:03 UTC, ssrihari commented on src/mars_rover/core.clj
> +  [[x y orientation :as state] instruction]
this function is not returning the "final" position.. it returns the position after processing **one** instruction.

2021-08-09 09:03 UTC, ssrihari commented on src/mars_rover/core.clj
> +      (recur (+ 2 index)))))
Do you really need the loop?

2021-08-09 09:03 UTC, ssrihari commented on src/mars_rover/core.clj
> +        (catch Exception e (str "caught exception: " (.getMessage e))))
Alignment: `(catch Exception e` in one line, the body of the `catch` in another line.

2021-08-11 07:42 UTC, PriyangaPKini commented on test/mars_rover/core_test.clj
> +  (testing "when rover is taken to the edge of the plateau while executing the instructions"))
Will be updated soon after fixing the exception handling

2021-08-11 07:46 UTC, PriyangaPKini commented on src/mars_rover/core.clj
> +      (catch Exception e
Need to fix exception handling here. Not able to catch the error I am throwing from other function.

2021-08-17 03:40 UTC, merged